name: Production CI

on:
  push:
    branches:
      - master

jobs:
  js-install-and-test:
    name: Build Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [v16.7]  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies, Test, and Build
      run: |
        yarn install --frozen-lockfile --check-files
        yarn lint
        yarn test
      env:
        CI: true

  build-and-push-docker-image:
    name: Build and Push image to DockerHub
    needs: [js-install-and-test]
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: mgraman/littlelink:latest